matrix:
  include:
  - os: windows
    language: node_js
    node_js:
    - 8
    before_install:
    - echo $OUTPUT_PATH $TRAVIS_TAG
    - powershell Install-WindowsFeature Net-Framework-Core
    - choco install wixtoolset
    - export PATH=$PATH:";C:\Program Files (x86)\WiX Toolset v3.11\bin"
    install:
    - bash dist/make --build --sign
    script: skip     #skip tests 
    deploy:
      provider: releases
      api_key:
         secure: $GITHUB_TOKEN
      file_glob: true
      file: ./*.msi
      skip_cleanup: true
      on:
         tags: true
