name: tests
on: [push]
jobs:
  tests:
    runs-on: windows-2019
    environment: production
    defaults:
      run:
        shell: wslbash.exe
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '8.x'
    - run: powershell Install-WindowsFeature Net-Framework-Core
    - run: npm install
    - run: bash dist/make --build

